import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-gray-100 min-h-screen`}
      >
        <AuthProvider>
          <Navbar />

          {children}
          <Toaster  position="top-right"/>
        </AuthProvider>
      </body>
    </html>
  );
}
